apiVersion: apps/v1
kind: Deployment
metadata:
  name: sustainability-platform
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sustainability
  template:
    metadata:
      labels:
        app: sustainability
    spec:
      containers:
      - name: app
        image: your-docker-image
        ports:
        - containerPort: 8080